---
# handlers file for mariadb
 
  - name: start_mysql
    service:
      name: mariadb 
      state: started
      enabled: true

  - name: restart_mysql
    service:
      name: mariadb
      state: restarted
  
  - name: restart_httpd
    service: 
      name: httpd
      state: restarted 

