# vsftpd/tasks/main.yml

- name: Install packages
  yum:
    pkg: "{{ item }}"
    state: present
  with_items:
    - vsftpd

- name: Allow FTP service through firewall
  firewalld: service=ftp permanent=true state=enabled
  notify: restart firewalld

- name: Configure vsftp
  template:
    src: vsftpd.conf.j2
    dest: /etc/vsftpd/vsftpd.conf

- name: Start and ensure the vsftpd service starts at boot
  service:
    name: vsftpd
    state: started
    enabled: yes
