---

- name: restart autofs 
  service:
    name: autofs
    state: restarted

- name: restart nslcd 
  service:
    name: nslcd
    state: restarted

- name: restart sshd 
  service:
    name: sshd
    state: restarted
