---
# tasks file for nagios_clients
   


  - name: Install Epel Repo
    yum: 
      name: epel-release
      state: latest 

  - name: Install NRPE and Common Plugins
    yum: 
      name: ['nrpe', 'nagios-plugins-all'] 
      state: latest
      lock_timeout: 180


  - name: Setup NRPE client configuration
    lineinfile: 
      path: /etc/nagios/nrpe.cfg
      regexp: '^ allowed_hosts=127.0.0.1'
      line: allowed_hosts=127.0.0.1,192.168.41.34

  - name: Start NRPE service
    service:
      name:  nrpe
      state: started 
      enabled: true 


