---
- name: Demo for SampleApp-Server
  hosts: jenkins
  remote_user: ansible
  become: yes

  tasks:
    - name: Update the software package repository
      yum:
        name: "*"
        update_cache: yes
    - name: Install dependencies
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - java
        - wget
    - name: Download jenkins repo
      command: wget -O /etc/yum.repos.d/jenkins.repo https://pkg.jenkins.io/redhat-stable/jenkins.repo

    - name: Import Jenkins CI key
      rpm_key:
        key: https://jenkins-ci.org/redhat/jenkins-ci.org.key
        state: present

    - name: Install Jenkins
      yum:
        name: jenkins
        state: latest

    - firewalld:
        zone: public
        port: 8080/tcp
        permanent: yes
        state: enabled


    - name: Start the server
      service:
        name: jenkins
        state: started

    - name: enable the server
      service:
        name: jenkins
        enabled: yes

